### ISSUE TITLE
TypeError for latest version of `bun-plugin-html`

### ISSUE THREAD

**Issue by BjornTheProgrammer** [BjornTheProgrammer/bun-plugin-html#20]
Described by @mindon in #19 for v2.2.0, which now has been unpublished off npm.
> there's one issue when i use this with <https://github.com/mindon/bun.lit-and-mw3.demo>:
> 
> ```shell
> TypeError: undefined is not an object (evaluating 'G._Universe_findRule(L, W._primary)[B]')
>       at _Parser_handleIdentifier (dist/index.js:8:101916)
>       at _Parser_parse (dist/index.js:8:99960)
>       at _Universe_evalInEnvironment (dist/index.js:8:94903)
>       at toList$1$growable (dist/index.js:83:128503)
>       at SourceFile$fromString (dist/index.js:28:5418)
>       at SpanScanner$ (dist/index.js:51:3251)
>       at ScssParser$0 (dist/index.js:61:29547)
>       at BuiltInCallable$function0 (dist/index.js:51:36339)
>       at call$0 (dist/index.js:202:23700)
>       at dist/index.js:8:17290
> ```
> 
> if **bun-plugin-html** is built with **minify: false** - then no such error

**Comment by BjornTheProgrammer** [comment]
This appears to be an issue with the Bun bundler itself, I filed the issue at https://github.com/oven-sh/bun/issues/15441.

A minimal reproduction of this issue exists at [bun-sass-issue](https://github.com/BjornTheProgrammer/bun-sass-issue).

**Comment by BjornTheProgrammer** [comment]
Fixed with #22
